<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Suvetha Babu" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>SDS 348 Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project2/">SDS 348 Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         April 28, 2021 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<p>Introduction:</p>
<p>I chose to analyze the ‘FaithfulFaces’ dataset, regarding a study of college students and their observations of a photograph of a person of the opposite sex. The students then rated the person in the photograph on a scale from 1 to 10 for attractiveness (‘Attract’), trustworthiness (‘Trust’), faithfulness (‘Faithful’), sexual dimorphism (how distinctly masculine as a male or feminine as a female they appear) (‘SexDimorph’). The person in the photograph’s sex (‘FaceSex’), the rater’s sex (‘RaterSex’), and whether or not the person in the photo was unfaithful in a past relationship (‘Cheater’) was all recorded, to make a total of 7 variables. There were 170 total observations recorded in total.</p>
<p>I believe people who score more sexually dimorphic (appearing more masculine or feminine) would be rated as more likely to be unfaithful. I don’t think there will be as clear of a relationship between attractiveness and faithfulness (as in people who are rated as more attracted being also rated as more unfaithful) because people are inclined to trust those they find attractive and may not be as quickly inclined to rate them as unfaithful. I do still believe there will be somewhat of a relationship there though. However, I don’t believe that either of these factors (being attractive or sexually dimorphic) will have a relationship with whether or not the person in the photo is actually a cheater/faithful.</p>
<pre class="r"><code>#importing dataset
library(readr)
FaithfulFaces &lt;- read_csv(&quot;~/SDS348_notshared/FaithfulFaces.csv&quot;)</code></pre>
<p>Part 1: MANOVA Testing</p>
<pre class="r"><code>man &lt;- manova(cbind(SexDimorph, Faithful, Attract, Trust)~FaceSex, data=FaithfulFaces)
summary(man) #test that at least either sexdimorph/faithful/attract/trust differ by facesex</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## FaceSex 1 0.20961 10.939 4 165 6.827e-08 ***
## Residuals 168
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man) #which (sexdimorph/faithful/attract/trust) differ by facesex</code></pre>
<pre><code>## Response SexDimorph :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## FaceSex 1 12.36 12.3598 13.885 0.0002652 ***
## Residuals 168 149.55 0.8902
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response Faithful :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## FaceSex 1 27.229 27.2293 35.823 1.27e-08 ***
## Residuals 168 127.698 0.7601
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response Attract :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## FaceSex 1 0.363 0.36264 0.4798 0.4895
## Residuals 168 126.982 0.75584
##
## Response Trust :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## FaceSex 1 2.314 2.31372 3.7592 0.05419 .
## Residuals 168 103.401 0.61548
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>#5 total tests

1 - (0.95^5) #prob of at least one type-I error</code></pre>
<pre><code>## [1] 0.2262191</code></pre>
<pre class="r"><code>0.05/5 #bonferroni correction</code></pre>
<pre><code>## [1] 0.01</code></pre>
<pre class="r"><code>library(rstatix)
group &lt;- FaithfulFaces$FaceSex
DVs &lt;- FaithfulFaces %&gt;% select(SexDimorph, Faithful, Attract, Trust)
#Test multivariate normality for each group (null: normality met)
sapply(split(DVs,group), mshapiro_test)</code></pre>
<pre><code>##           F            M        
## statistic 0.926527     0.9828878
## p.value   0.0001623905 0.2989608</code></pre>
<pre class="r"><code>#Box&#39;s M test (null: homogeneity of vcov mats assumption met)
box_m(DVs, group)</code></pre>
<pre><code>## # A tibble: 1 x 4
## statistic p.value parameter method
## &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;
## 1 46.7 0.00000109 10 Box&#39;s M-test for Homogeneity of
Covariance Matrices</code></pre>
<p>Significant differences were found between male and females rated for at least one of the dependent variables, Pillaitrace = 0.20961, pseudoF(4,165) = 10.939, p = 6.827e-08. There were five tests conducted in total (1 MANOVA, 4 univariate ANOVAs), resulting in 0.2262191 as the probability of at least one type-I error, and a Bonferroni correction of 0.01 was used to combat this. There was no need to use t-tests to conduct post-hoc analyses as the ‘FaceSex’ variable only had two groups, so the information about which groups differed was given in the univariate ANOVAs. ‘SexDimorph’ and ‘Faithful’ were significant - males and females rated significantly differ in sexual dimorphism and faithfulness ratings, F(1,168) = 13.885, p = 0.0002652 and F(2,147) = 35.823, p = 1.27e-08, respectively. There are a large number of assumptions for the MANOVA test and oftentimes it is difficult for all of them to be met. In this case, the multivariate normality and homogeneity of within-group covariance matrices assumptions are not met. There is also likely preexisting relationships between dependent variables which violates the multicollinearity assumption.</p>
<p>Part 2: Randomization Test</p>
<pre class="r"><code>FaithfulFaces %&gt;% group_by(RaterSex) %&gt;% summarize(means=mean(Trust)) %&gt;% summarize(`mean_diff1`=diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   mean_diff1
##        &lt;dbl&gt;
## 1      0.233</code></pre>
<pre class="r"><code>#men score women about 0.23 points higher on trust than women score men

set.seed(348)

rand_dist&lt;-vector() #create vector to hold diffs under null hypothesis

for(i in 1:5000){
new&lt;-data.frame(Trust=sample(FaithfulFaces$Trust),RaterSex=FaithfulFaces$RaterSex) #scramble columns
rand_dist[i]&lt;-mean(new[new$RaterSex==&quot;M&quot;,]$Trust)-   
              mean(new[new$RaterSex==&quot;F&quot;,]$Trust)} #compute mean difference 

mean(rand_dist&gt;0.2334701    | rand_dist&lt; -0.2334701) #two-tailed p value</code></pre>
<pre><code>## [1] 0.047</code></pre>
<pre class="r"><code>#significant

{hist(rand_dist,main=&quot;&quot;,ylab=&quot;&quot;); abline(v = c(-0.2334701, 0.2334701),col=&quot;red&quot;)}</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" />
The null hypothesis is that there is no mean difference in ‘Trust’ ratings between male and female raters, while the alternative is there is a significant difference in trust ratings male and female raters. Male raters score the women they are rating significantly higher in ‘Trust’ value on average by than female raters score the men they are rating (p = 0.047).</p>
<p>Part 3: Linear Regression Model</p>
<pre class="r"><code>#Faithfulness score predicted by sexdimorphic and trust

#mean centering numerics involved in interaction
FaithfulFaces$SexDimorph_c &lt;- FaithfulFaces$SexDimorph - mean(FaithfulFaces$SexDimorph, na.rm = T)
FaithfulFaces$Trust_c &lt;- FaithfulFaces$Trust - mean(FaithfulFaces$Trust, na.rm = T)

fit &lt;- lm(Faithful~SexDimorph_c*Trust_c,data=FaithfulFaces)
summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = Faithful ~ SexDimorph_c * Trust_c, data =
FaithfulFaces)
##
## Residuals:
## Min 1Q Median 3Q Max
## -1.68491 -0.47230 0.00223 0.44144 1.67459
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 5.140726 0.049428 104.004 &lt; 2e-16 ***
## SexDimorph_c -0.555323 0.051003 -10.888 &lt; 2e-16 ***
## Trust_c 0.538840 0.063953 8.426 1.64e-14 ***
## SexDimorph_c:Trust_c 0.006641 0.061253 0.108 0.914
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 0.6431 on 166 degrees of
freedom
## Multiple R-squared: 0.5569, Adjusted R-squared: 0.5489
## F-statistic: 69.54 on 3 and 166 DF, p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>#graph
new1&lt;-FaithfulFaces
new1$Trust_c&lt;-mean(FaithfulFaces$Trust_c)
new1$mean&lt;-predict(fit,new1)
new1$Trust_c&lt;-mean(FaithfulFaces$Trust_c)+sd(FaithfulFaces$Trust_c)
new1$plus.sd&lt;-predict(fit,new1)
new1$Trust_c&lt;-mean(FaithfulFaces$Trust_c)-sd(FaithfulFaces$Trust_c)
new1$minus.sd&lt;-predict(fit,new1)
newint&lt;-new1%&gt;%select(Faithful,SexDimorph_c,mean,plus.sd,minus.sd)%&gt;%gather(Trust,value,-Faithful,-SexDimorph_c)

mycols&lt;-c(&quot;#619CFF&quot;,&quot;#F8766D&quot;,&quot;#00BA38&quot;)
names(mycols)&lt;-c(&quot;-1 sd&quot;,&quot;mean&quot;,&quot;+1 sd&quot;)
mycols=as.factor(mycols)

ggplot(FaithfulFaces,aes(SexDimorph_c,Faithful),group=mycols)+geom_point()+geom_line(data=new1,aes(y=mean,color=&quot;mean&quot;))+geom_line(data=new1,aes(y=plus.sd,color=&quot;+1 sd&quot;))+geom_line(data=new1,aes(y=minus.sd,color=&quot;-1 sd&quot;))+scale_color_manual(values=mycols)+labs(color=&quot;Trust (cont)&quot;)+theme(legend.position=c(.9,.2))</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#linearity and homoskedsaticity assumption
resids&lt;-fit$residuals
fitvals&lt;-fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, color=&#39;red&#39;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#normality assumption
ks.test(resids, &quot;pnorm&quot;, mean=0, sd(resids)) #Ho: true distribution is normal</code></pre>
<pre><code>## 
##  One-sample Kolmogorov-Smirnov test
## 
## data:  resids
## D = 0.04963, p-value = 0.7965
## alternative hypothesis: two-sided</code></pre>
<pre class="r"><code>#formally checking homoskedsaticity
library(sandwich)
library(lmtest)
bptest(fit) #h0 = homoskedastic; don&#39;t need robust standard errors</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 3.5369, df = 3, p-value = 0.316</code></pre>
<pre class="r"><code>coeftest(fit) #normal-theory SEs</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 5.1407260 0.0494284 104.0036 &lt; 2.2e-16 ***
## SexDimorph_c -0.5553226 0.0510028 -10.8881 &lt; 2.2e-16 ***
## Trust_c 0.5388402 0.0639533 8.4255 1.635e-14 ***
## SexDimorph_c:Trust_c 0.0066413 0.0612525 0.1084 0.9138
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>coeftest(fit, vcov = vcovHC(fit)) #robust SEs</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 5.1407260 0.0501229 102.5624 &lt;2e-16 ***
## SexDimorph_c -0.5553226 0.0499749 -11.1120 &lt;2e-16 ***
## Trust_c 0.5388402 0.0586822 9.1824 &lt;2e-16 ***
## SexDimorph_c:Trust_c 0.0066413 0.0505335 0.1314 0.8956
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>#Sexdimorph and trust explain a significant amount of variation in faithful</code></pre>
<p>Predicted ‘Faithful’ rating for a person with average ‘SexDimorphic’ rating and average ‘Trust’ rating is 5.140726. When controlling for ‘Trust’, for every one unit in increase in ‘SexDimorph’ rating, ‘Faithful’ rating decreases by 0.555323. Controlling for ‘SexDimorph’, for every one unit in increase in ‘Trust’ rating, ‘Faithful’ rating increases by 0.538840. The interaction means that the magnitude of the relationship between ‘SexDimorph’ and ‘Faithful’ depend on ‘Trust’. The main effects of ‘mean-centered SexDimorph’ (t = -11.1120, df = 166, p &lt; 2e-16) and ‘mean-centered Trust’ (t = 9.1824, df = 166, p &lt; 2e-16) on ‘Faithful’ are both significant, but the interaction between ‘Sexdimorph’ and ‘Trust’ is not significant.
The assumptions of linearity, normality, and homoskedasticity are met by this model - checked both graphically and using hypothesis testing. This model explains 54.89% of the variation in the outcome. There is no change in the significance of results after using robust standard errors because the homoskedsaticity assumption was met, so it wasn’t necessary to use robust SEs.</p>
<p>Part 4: Linear Regression Model with Bootstrapped Standard Errors</p>
<pre class="r"><code>#bootstrapped SEs by resampling residuals

fit1&lt;-lm(Faithful~SexDimorph_c*Trust_c,data=FaithfulFaces) #fit model  
resids&lt;-fit1$residuals #save residuals  
fitted&lt;-fit1$fitted.values #save yhats

resid_resamp&lt;-replicate(5000,{
  new_resids&lt;-sample(resids,replace=TRUE) #resample resids w/ replacement
  FaithfulFaces$new_y&lt;-fitted+new_resids #add new resids to yhats to get new &quot;data&quot;
  fit1&lt;-lm(new_y~SexDimorph_c*Trust_c,data=FaithfulFaces) #refit model
  coef(fit1) #save coefficient estimates (b0, b1, etc)
})

## Estimated SEs
resid_resamp%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>## (Intercept) SexDimorph_c Trust_c SexDimorph_c:Trust_c
## 1 0.04950917 0.05065432 0.06246773 0.06016783</code></pre>
<pre class="r"><code>## Normal-theory SEs
coeftest(fit)[,1:2]</code></pre>
<pre><code>##                          Estimate Std. Error
## (Intercept)           5.140726015 0.04942837
## SexDimorph_c         -0.555322583 0.05100277
## Trust_c               0.538840163 0.06395332
## SexDimorph_c:Trust_c  0.006641296 0.06125253</code></pre>
<pre class="r"><code>## Robust SEs
coeftest(fit, vcov=vcovHC(fit))[,1:2]</code></pre>
<pre><code>##                          Estimate Std. Error
## (Intercept)           5.140726015 0.05012293
## SexDimorph_c         -0.555322583 0.04997491
## Trust_c               0.538840163 0.05868215
## SexDimorph_c:Trust_c  0.006641296 0.05053348</code></pre>
<p>The bootstrapped standard errors were nearly identical to the standard errors derived from the normal-theory. The robust standard errors were also quite similar to those values but a little smaller.</p>
<p>Part 5: Logistic Regression Model from 2 Explanatory Variables</p>
<pre class="r"><code>#predict cheater from 2 variables

logfit&lt;-glm(Cheater~Trust+Attract, data=FaithfulFaces, family=&quot;binomial&quot;)
coeftest(logfit)</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##             Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -0.22144    0.97526 -0.2271   0.8204
## Trust       -0.16670    0.23030 -0.7238   0.4692
## Attract      0.02118    0.20950  0.1011   0.9195</code></pre>
<pre class="r"><code>exp(coeftest(logfit))</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##             Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)  0.80136    2.65185  0.7969    2.271
## Trust        0.84645    1.25897  0.4849    1.599
## Attract      1.02141    1.23307  1.1064    2.508</code></pre>
<pre class="r"><code>class_diag &lt;- function(probs,truth){
  #CONFUSION MATRIX: CALCULATE ACCURACY, TPR, TNR, PPV
  
  if(is.character(truth)==TRUE) truth&lt;-as.factor(truth)
  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),factor(truth, levels=c(0,1)))
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]
  
  #CALCULATE EXACT AUC
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup &lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR &lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  n &lt;- length(TPR)
  auc &lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,auc)
}

probs&lt;-predict(logfit,type=&quot;response&quot;)
class_diag(probs, FaithfulFaces$Cheater)</code></pre>
<pre><code>##         acc sens spec ppv       auc
## 1 0.7058824    0    1 NaN 0.5314167</code></pre>
<pre class="r"><code>##Confusion matrix
table(predict=as.numeric(probs&gt;.5),truth=FaithfulFaces$Cheater)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict   0   1 Sum
##     0   120  50 170
##     Sum 120  50 170</code></pre>
<pre class="r"><code>#Density plot of log-odds for each outcome
FaithfulFaces$logit&lt;-predict(logfit,type=&quot;link&quot;) #get log-odds for everyone

FaithfulFaces %&gt;% mutate(Cheater=as.factor(Cheater)) %&gt;% 
  ggplot() + geom_density(aes(logit, fill=Cheater), alpha=.4) + 
  theme(legend.position=c(.85,.85)) + xlab(&quot;logit (log-odds)&quot;) + geom_rug(aes(logit,color=Cheater))</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#ROC plot
library(plotROC)
ROCplot&lt;-ggplot(FaithfulFaces)+geom_roc(aes(d=Cheater,m=probs), n.cuts=0)+  geom_segment(aes(x=0,xend=1,y=0,yend=1),lty=2)
ROCplot</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.5314167</code></pre>
<p>Controlling for ‘Attract’ ratings, for every 1-unit increase in ‘Trust’, odds of being a cheater change by a factor of 0.84645. Controlling for ‘Trust’ ratings, for every 1-unit increase in ‘Attract’, odds of being a cheater change by a factor of 1.02141. The accuracy is value is 0.7058824. The sensitivity, specificity, and precision are 0, 1, and NaN respectively due to having no true or false positives. The AUC value of the model is 0.5314167, which is pretty bad. The ROC plot is not very good, and the resulting AUC value is the same as the model, 0.5314167 - it is difficult to predict whether or not the person rated is a cheater based on their scores for attractiveness and trustworthiness.</p>
<p>Part 6: Logistic Regression Model from the Rest of the Variables</p>
<pre class="r"><code>#predict cheater from all of the variables

logfit2&lt;-glm(Cheater~(.), data=FaithfulFaces, family=&quot;binomial&quot;)
coeftest(logfit2)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) 3.7769030 2.0473457 1.8448 0.0650695 .
## X1 -0.0256570 0.0077639 -3.3047 0.0009509 ***
## SexDimorph -0.5514692 0.2868713 -1.9224 0.0545608 .
## Attract 0.2385767 0.3266404 0.7304 0.4651485
## Trust 0.0231795 0.3349212 0.0692 0.9448234
## Faithful -0.4350656 0.3113129 -1.3975 0.1622576
## FaceSexM 2.2440669 0.8050493 2.7875 0.0053118 **
## RaterSexM NA NA NA NA
## SexDimorph_c NA NA NA NA
## Trust_c NA NA NA NA
## logit NA NA NA NA
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coeftest(logfit2))</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##              Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)  43.68055    7.74731  6.3267    1.067
## X1            0.97467    1.00779  0.0367    1.001
## SexDimorph    0.57610    1.33225  0.1463    1.056
## Attract       1.26944    1.38630  2.0759    1.592
## Trust         1.02345    1.39783  1.0717    2.572
## Faithful      0.64722    1.36522  0.2472    1.176
## FaceSexM      9.43161    2.23681 16.2402    1.005
## RaterSexM          NA         NA      NA       NA
## SexDimorph_c       NA         NA      NA       NA
## Trust_c            NA         NA      NA       NA
## logit              NA         NA      NA       NA</code></pre>
<pre class="r"><code>probs2&lt;-predict(logfit2,type=&quot;response&quot;)

##Confusion matrix
table(predict=as.numeric(probs2&gt;.5),truth=FaithfulFaces$Cheater)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict   0   1 Sum
##     0   112  39 151
##     1     8  11  19
##     Sum 120  50 170</code></pre>
<pre class="r"><code>class_diag(probs2, FaithfulFaces$Cheater)</code></pre>
<pre><code>##         acc sens      spec       ppv       auc
## 1 0.7235294 0.22 0.9333333 0.5789474 0.6878333</code></pre>
<pre class="r"><code>##10-FOLD CV

set.seed(1234)
k=10

data1&lt;-FaithfulFaces[sample(nrow(FaithfulFaces)),] 
folds&lt;-cut(seq(1:nrow(FaithfulFaces)),breaks=k,labels=F) 

diags1_cv&lt;-NULL
for(i in 1:k){          
train&lt;-data1[folds!=i,]
test&lt;-data1[folds==i,]  

truth&lt;-test$Cheater

fit1_cv &lt;- glm(Cheater~(.), family=&quot;binomial&quot;, data=train)
probs1_cv &lt;- predict(fit1_cv, type=&quot;response&quot;, newdata=test)

diags1_cv &lt;-rbind(diags1_cv,class_diag(probs1_cv,truth)) 
}

summarize_all(diags1_cv,mean) </code></pre>
<pre><code>##         acc   sens      spec ppv       auc
## 1 0.6705882 0.1325 0.8865551 NaN 0.6316558</code></pre>
<pre class="r"><code>##LASSO

#install.packages(&quot;glmnet&quot;)
library(glmnet)

set.seed(1234)

y&lt;-as.matrix(FaithfulFaces$Cheater) #grab response
x&lt;-model.matrix(logfit2)[,-1] #grab predictors

cv&lt;-cv.glmnet(x,y,family=&quot;binomial&quot;)
lasso&lt;-glmnet(x,y,family=&quot;binomial&quot;,lambda=cv$lambda.1se)
coef(lasso)</code></pre>
<pre><code>## 11 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                      s0
## (Intercept)  -0.8754687
## X1            0.0000000
## SexDimorph    .        
## Attract       .        
## Trust         .        
## Faithful      .        
## FaceSexM      .        
## RaterSexM     .        
## SexDimorph_c  .        
## Trust_c       .        
## logit         .</code></pre>
<p>The accuracy value is 0.723529. The sensitivity, specificity, and precision values are 0.22, 0.9333333, and 0.5789474 respectively. The AUC value is 0.6878333, which is still poor but better than the model with only two predictor variables. Upon running the 10-fold CV with the same model, the accuracy value obtained is 0.6705882. The sensitivity, specificity, and precision values are 0.1325, 0.8865551, and NaN respectively. They have all decreased. The AUC value is 0.6316558, which has decreased as well in comparison to the previous statistics.
Unfortunately, when conducting lasso, none of the variables were significant and could not be retained to rerun the model with their values only included (X1 is just an observation/index variable). It appears that none of the variables could significantly predict whether or not the person being rated is a cheater.</p>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
